os: linux

dist: bionic

env: IRAFARCH=linux64

addons:
  apt:
    packages:
      - xutils-dev
      - csh
      - libxt-dev
      - libncurses-dev
      - libxaw7-dev
      - libxmu-dev
      - libxpm-dev
      - xaw3dg-dev
      - tcl-dev
      - iraf-dev
      - xauth
      - xvfb
      
language: c

cache:
  ccache: true
  directories:
    - $HOME/.ccache

git:
  depth: 3

before_script:
  - make

script:
  - test -x xgterm/xgterm
  - test -x ximtool/ximtool
  - test -x ximtool/clients/ism_wcspix.e
  - xvfb-run xgterm/xgterm -e sleep 1
